### ISSUE TITLE
OS: Window 10, Internet Explorer 11 heatmap not rendering at all.

### ISSUE THREAD

**Issue by StevanSkrbic** [kevinsqi/react-calendar-heatmap#69]
On OS: Window 10 in browser: Internet Explorer 11
heatmap is not rendering at all.

**Comment by StevanSkrbic** [comment]
Fixed with adding babel-polyfill as a dependencie in project package.json.

**Comment by andreysaleba** [comment]
Hey, I've added PR with that change #70

**Comment by kevinsqi** [comment]
This might be due to the use of ES6 `Array.from` which [doesn't seem to be supported by IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from). If [this bit of code](https://github.com/okize/react-calendar-heatmap/blob/master/src/helpers.js#L22) is switched to use ES5 or lodash.range or just-range, I suspect that IE11 will work again. Need to test  out this hypothesis though.

**Comment by kevinsqi** [comment]
This should be fixed with v1.8.1 - I've verified in IE11/Win8 with VirtualBox at https://www.kevinqi.com/react-calendar-heatmap. Please reopen if there's still an issue.
